### ISSUE TITLE
webrick uses "0.0.0.0:3000" which doesn't support subdomains

### ISSUE THREAD

**Issue by ghost** [fortuity/rails3-subdomain-devise#1]
Hey this is a great app, btw!

I was testing this out when I ran into a problem. "rails server" launches webrick by default, and webrick runs "0.0.0.0:3000", but the README says the app will run at "localhost:3000". 

so after creating a subdomain, webrick was redirected to "subdomain.:3000" which fails of course. I'm a n00b so maybe there's a quick fix for this, but I think a lot of folks are going to be confused by this. Maybe you could add a line to the README about using mongrel for testing the app? that way "localhost:3000" will be the default and the subdomains will work?

Thanks,

Gabe

**Comment by fortuity** [comment]
What platform/OS are you using? On Mac OS (as with any *nix platform), "localhost" is an alias for 0.0.0.0 so you should be able to use http://localhost:3000/ or http://lvh.me:3000/ to access the app. Have you tried either of those?

**Comment by ghost** [comment]
Just tried with Mongrel and it does the same thing, so I guess Webrick isn't the issue. I launched my server using "rails server -b localhost" which got me to localhost:3000, but subdomains still don't work. Sorry this issue is getting a bit off-topic. I think I just need to keep at it. :)

**Comment by fortuity** [comment]
Did you read the README section titled "Test the App"?

Let me know if it needs to be more clear (if you read it) and I will try to explain better.

Right now it says:

You can check that your app runs properly by entering the command

$ rails server (or, abbreviated: $ rails s)

If you launch the application, it will be running at http://localhost:3000/. However, unless you’ve made some configuration changes to your computer, you won’t be able to resolve an address that uses a subdomain, such as http://foo.localhost:3000/. There are several complex solutions to this problem. You could set up your own domain name server on your localhost and create an A entry to catch all subdomains. You could modify your /etc/hosts file (but it won’t accommodate dynamically created subdomains). You can create a proxy auto-config file and set it up as the proxy in your web browser preferences. There’s a far simpler solution that does not require reconfiguring your computer or web browser preferences. The developer Levi Cook registered a domain, lvh.me (short for: local virtual host me), that resolves to the localhost IP address 127.0.0.1 and supports wildcards (accommodating dynamically created subdomains). See Tim Pope’s blog post for a NSFW alternative.

To test the application, visit http://lvh.me:3000/. You can also try http://foo.lvh.me:3000/ or http://bar.lvh.me:3000/.

**Comment by ghost** [comment]
Ah everything works now. I think for me personally, it would be clearer if the README said "If you launch the application, it will be running at http://localhost:3000/ or http://0.0.0.0:3000." I got hung up on the fact that my app was running at 0.0.0.0:3000 and not localhost.... anyways, thanks for the help!

**Comment by fortuity** [comment]
Glad to hear all works for you. I've updated the README per your suggestion. Thanks for the contribution.
