### ISSUE TITLE
Ignoring "www" in subdomains

### ISSUE THREAD

**Issue by bigfolio** [fortuity/rails3-subdomain-devise#2]
I added the following route right above the other match '/' route:

match '/' => 'home#index', :constraints => { :subdomain => 'www' }

This will intercept the "www" subdomain first, then the limit_subdomain_access before filter will redirect to root, effectively getting rid of the "www"

Only issue is you need to prevent users from creating a subdomain called "www" (but this probably should be done anyway).

**Comment by fortuity** [comment]
Excellent contribution! Thank you.

**Comment by fortuity** [comment]
I've added this to the tutorial and to the example code.

-- Daniel
