### ISSUE TITLE
open_http - error 406

### ISSUE THREAD

**Issue by ghost** [fortuity/rails3-subdomain-devise#3]
Hello! This is a great app, but I can't get it to work. My "rails new" command fails due to open_http errors. Any advice or tips would be much appreciated. I'm running rails 3.0.0 and ruby 1.9.2-p0.  http://pastie.org/1141710

Thanks in advance,

Gabe

**Comment by fortuity** [comment]
Hi Gabe,

Looks like you have the wrong file name in your command. You have:
rails new trial -m 'http://github.com/fortuity/rails3-subdomain-devise.git'

It should be:

rails new trial -m http://github.com/fortuity/rails3-subdomain-devise/raw/master/template.rb

I tested and it works. Let me know if it works for you. And let me know if there is an error in the tutorial or readme file, please.

Good luck!
-- Daniel

**Comment by ghost** [comment]
Ah! I was mixing up "git clone" and "rails new". Thanks for the quick reply. I'm surprised "rails new" got me as far as it did. Thanks!
