### ISSUE TITLE
Using Subdomains in emails

### ISSUE THREAD

**Issue by tomato** [fortuity/rails3-subdomain-devise#4]
Thanks for the great guide, its helped me a lot. I have been trying to get my devise mails to use the subdomain and eventually found a simple solution. In the suggested UrlHelper I added
    def set_mailer_url_options
      ActionMailer::Base.default_url_options[:host] = with_subdomain(request.subdomain)
    end
then added
    before_filter :set_mailer_url_options
to ApplicationController
Hope this is useful and not really obvious!

**Comment by fortuity** [comment]
Tom,

Thanks for figuring this out and making the suggestion. I'm sure this will be useful!

Just to clarify, you said you added 

```
  before_filter :set_mailer_url_options
```

Did you add that to the ApplicationController?

Thanks,
Daniel

**Comment by tomato** [comment]
Yes thats right in ActionController. 
Cheers
Tom

**Comment by fortuity** [comment]
I've updated the tutorial and added the suggested code to the app. Thanks!

**Comment by tomato** [comment]
Thats great, thanks for the credits. Its my first contribution to any open source project and has definitely inspired me to do more. Feels good!

**Comment by fortuity** [comment]
Oh, cool! Glad I can encourage you :-)

-- Daniel
