### ISSUE TITLE
gem "jquery-rails", "0.2.4" can rot in hell!

### ISSUE THREAD

**Issue by pjammer** [fortuity/rails3-subdomain-devise#6]
This "gem" caused all of my destroy links NOT to work.

I don't know why, or how, nor do i Care, as I'm on a deadline right  now.

For anyone else, this is for you.

**Comment by fortuity** [comment]
Thanks for taking the time to report this issue for everyone's benefit.

I've updated the application generator template to use jquery-rails v0.2.6 and tested the app. The issue appears to be resolved.

-- Daniel
